import compression from 'compression';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import { pinoHttp } from 'pino-http';
import swaggerUi from 'swagger-ui-express';
import { env } from './config/env.js';
import { logger } from './config/logger.js';
import { openApiDocument } from './config/openapi.js';
import { errorHandler } from './common/middleware/error-handler.js';
import { requestIdMiddleware } from './common/middleware/request-id.js';
import { generalRateLimit } from './common/security/rate-limits.js';
import { authRoutes } from './modules/auth/auth.routes.js';
import { childrenRoutes } from './modules/children/children.routes.js';
import { healthRoutes } from './modules/health/health.routes.js';
import { hospitalsRoutes } from './modules/hospitals/hospitals.routes.js';
import { schoolsRoutes } from './modules/schools/index.js';
import { screeningRoutes } from './modules/screening/index.js';
export const createApp = () => {
  const app = express();
  app.disable('x-powered-by');
  app.use(requestIdMiddleware);
  app.use(pinoHttp({ logger }));
  app.use(helmet());
  app.use(cors({ origin: env.APP_ORIGIN, credentials: true }));
  app.use(compression());
  app.use(express.json({ limit: '1mb' }));
  app.use(cookieParser());
  app.use(generalRateLimit);
  app.use('/health', healthRoutes);
  app.use('/api/docs', swaggerUi.serve, swaggerUi.setup(openApiDocument));
  app.use('/api/v1/auth', authRoutes);
  app.use('/api/v1/children', childrenRoutes);
  app.use('/api/v1/hospitals', hospitalsRoutes);
  app.use('/api/v1/schools', schoolsRoutes);
  app.use('/api/v1/screening', screeningRoutes);
  app.use(errorHandler);
  return app;
};
